siteName: A-level retakes
title: A-level retakes
author: David White
url: https://github.com/webdigga/a-level-retakes
poweredBy: Arragon Affiliates
description: A-level retakes, courses, and private tuition
type: website
logoAlt: A-level retakes Logo
logoUrl: /static/img/logo.png
